# Generated by Django 5.2.4 on 2025-07-27 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('location', models.CharField(max_length=100, verbose_name='Lugar')),
                ('image', models.ImageField(blank=True, null=True, upload_to='historical_facts/', verbose_name='Imagen')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Fuente')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historical_facts.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Hecho Histórico',
                'verbose_name_plural': 'Hechos Históricos',
                'ordering': ['-date'],
            },
        ),
    ]
